spring:
  config:
    import: file:.env[.properties]
  application:
    name: task-tracker
  security:
    android_user:
      name: andriod_user
      password: ${ANDRIOD_USER_PASSWORD}
      roles: [ANDRIOD]
    admin:
      name: admin
      password: ${ADMIN_PASSWORD}
      roles: [ANDRIOD]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081
